version: '3.8'

services:

  lizmap:
    image: 3liz/lizmap-web-client:${LIZMAP_VERSION_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_lizmap
    restart: ${RESTART_POLICY}
    command:
      - php-fpm
    environment:
      LIZMAP_CACHEREDISDB: '1'
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_CACHESTORAGETYPE: redis
      LIZMAP_HOME: /srv/lizmap
      LIZMAP_USER: ${LIZMAP_UID}
      # LIZMAP_WMSSERVERURL: http://${MAP_FQDN}:8080/ows/
      LIZMAP_WMSSERVERURL: http://qgismapserver:8080/ows/
      LIZMAP_CONFIG_INCLUDE: /srv/etc
    volumes:
      - ${LIZMAP_PROJECTS}:/srv/projects
      - ${LIZMAP_DIR}/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - ${LIZMAP_DIR}/var/lizmap-config:/www/lizmap/var/config
      - ${LIZMAP_DIR}/var/lizmap-db:/www/lizmap/var/db
      - ${LIZMAP_DIR}/www:/www/lizmap/www
      - ${LIZMAP_DIR}/www/var/log:/www/lizmap/var/log
      - ${LIZMAP_DIR}/var/lizmap-modules:/www/lizmap/lizmap-modules
      - ${LIZMAP_DIR}/var/lizmap-my-packages:/www/lizmap/my-packages
      - ${LIZMAP_DIR}/etc:/srv/etc:ro

  qgismapserver:
    image: 3liz/qgis-map-server:${QGIS_VERSION_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_QgisServer
    # hostname: ${MAP_FQDN}
    restart: ${RESTART_POLICY}
    environment:
      QGSRV_CACHE_SIZE: '20'
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_USER: ${LIZMAP_UID}:${LIZMAP_GID}
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_SERVER_WORKERS: ${QGIS_MAP_WORKERS}
      QGSRV_SERVER_PLUGINPATH: /srv/plugins
      API_ENABLED_LANDING_PAGE: 'yes'
      SERVER_CROSS_ORIGIN: 'yes'
      QGIS_OPTIONS_PATH: /srv/etc/qgis
    links:
      - postgis
    ports:
      - ${OWS_PORT}:8080
    volumes:
      - ${LIZMAP_PROJECTS}:/srv/projects
      - ${LIZMAP_DIR}/etc:/srv/etc:ro
      - ${LIZMAP_DIR}/wps-data:/srv/data

  redis:
    image: redis:5-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_Redis
    restart: ${RESTART_POLICY}
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:1
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: ${RESTART_POLICY}
    user: ${LIZMAP_UID}:${LIZMAP_UID}
    ports:
      - ${LIZMAP_PORT}:8080
    depends_on:
      - lizmap
    volumes:
      - ${LIZMAP_DIR}/etc/nginx.conf:/etc/nginx/nginx.conf
      - ${LIZMAP_DIR}/var/log/nginx:/var/log/nginx
      - ${LIZMAP_DIR}/var/nginx-cache:/var/cache/nginx
      - ${LIZMAP_DIR}:/srv/lizmap

  postgis:
    image: kartoza/postgis:${POSTGIS_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_postgis
    # hostname: ${POSTGRES_FQDN}
    restart: ${RESTART_POLICY}
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGSERVICEFILE: /etc/postgresql-common/pg_service.conf
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting,uuid-ossp
    ports:
      - ${POSTGIS_PORT}:5432
    healthcheck:
      test: "exit 0"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./postgis/qwat:/home/sample/qwat
      - ./postgis/sampleData:/home/sample/simple
      - ./postgis/exports:/home/exports
      - ./postgis/imports:/home/imports

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    restart: ${RESTART_POLICY}
    environment:
      PGADMIN_DEFAULT_EMAIL: gisadmin@gisadmin.com
      PGADMIN_DEFAULT_PASSWORD: gisadminsecret
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      # add server with env vars instead of file?
    ports:
      - 5050:80
    links:
      - postgis
    volumes:
       - ./pgadmin/config/servers.json:/pgadmin4/servers.json # preconfigured servers/connections

  filebrowser:
    image: filebrowser/filebrowser:v2.20.1
    container_name: ${COMPOSE_PROJECT_NAME}_filebrowser
    restart: ${RESTART_POLICY}
    volumes:
      - ${LIZMAP_PROJECTS}:/srv
      - ./filebrowser/filebrowser.db:/database.db
      - ./filebrowser/filebrowser.json:/.filebrowser.json
    ports:
      - ${FILEBROWSER_PORT}:80

  # geoserver:
  #   image: kartoza/geoserver:${GS_VERSION}
  #   container_name: ${COMPOSE_PROJECT_NAME}_geoserver
  #   restart: ${RESTART_POLICY}
  #   environment:
  #     - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
  #     - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
  #     - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
  #     - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
  #     - INITIAL_MEMORY=${INITIAL_MEMORY}
  #     - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
  #   depends_on:
  #     postgis:
  #       condition: service_healthy
  #   healthcheck:
  #     test: curl --fail -s http://localhost:8080/ || exit 1
  #     interval: 1m30s
  #     timeout: 10s
  #     retries: 3
  #   ports:
  #     - ${GEOSERVER_PORT}:8080
  #   volumes:
  #     - geoserver-data:/opt/geoserver/data_dir

  # drupal:
  #   container_name: ${COMPOSE_PROJECT_NAME}_Drupal
  #   image: drupal:8-apache
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - /var/www/html/modules
  #     - /var/www/html/profiles
  #     - /var/www/html/themes
  #     - /var/www/html/sites
  #   restart: always

#  geoserver-data:
  postgis_data:
    driver: local
  redis_data:
    driver: local
